# Generated by Django 5.2.1 on 2025-05-23 05:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Campaign Name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Daily Budget",
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Budget",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Creative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Creative Name"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("interstitial", "Interstitial"),
                            ("native", "Native"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                        verbose_name="Creative Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ad_creatives/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ad_videos/",
                        verbose_name="Video",
                    ),
                ),
                (
                    "call_to_action",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Call to Action"
                    ),
                ),
                ("destination_url", models.URLField(verbose_name="Destination URL")),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Width"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Height"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="advertising.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Creative",
                "verbose_name_plural": "Creatives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Device Type"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Operating System"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OS Version"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=2, verbose_name="Country"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Region"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "app_id",
                    models.CharField(blank=True, max_length=255, verbose_name="App ID"),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="App Version"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="advertising.creative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Impression",
                "verbose_name_plural": "Ad Impressions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "impression",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click",
                        to="advertising.adimpression",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="advertising.creative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Click",
                "verbose_name_plural": "Ad Clicks",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "os_android",
                    models.BooleanField(default=True, verbose_name="Android"),
                ),
                ("os_ios", models.BooleanField(default=True, verbose_name="iOS")),
                (
                    "os_version_min",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Minimum OS Version"
                    ),
                ),
                (
                    "os_version_max",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Maximum OS Version"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "age_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Minimum Age"
                    ),
                ),
                (
                    "age_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Age"
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Countries"
                    ),
                ),
                (
                    "regions",
                    models.JSONField(blank=True, default=list, verbose_name="Regions"),
                ),
                (
                    "cities",
                    models.JSONField(blank=True, default=list, verbose_name="Cities"),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Interests"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="advertising.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
            },
        ),
    ]
