# Generated by Django 5.2.1 on 2025-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0002_campaign_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="company_name",
            field=models.CharField(
                help_text="The company this campaign belongs to",
                max_length=255,
                verbose_name="Company Name",
            ),
        ),
    ]
