# Generated by Django 5.2.1 on 2025-05-23 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0003_alter_campaign_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Placement Name"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this placement",
                        max_length=100,
                        unique=True,
                        verbose_name="Placement Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "recommended_width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Recommended Width"
                    ),
                ),
                (
                    "recommended_height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Recommended Height"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Placement",
                "verbose_name_plural": "Placements",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="creative",
            name="placement",
            field=models.ForeignKey(
                blank=True,
                help_text="The placement location for this creative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creatives",
                to="advertising.placement",
            ),
        ),
    ]
