# Generated by Django 5.2.1 on 2025-05-23 16:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0004_placement_creative_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="daily_impression_target",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Target number of impressions per day",
                verbose_name="Daily Impression Target",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="opportunity_sampling_rate",
            field=models.FloatField(
                default=5.0,
                help_text="Percentage of traffic to sample for opportunity tracking",
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Opportunity Sampling Rate (%)",
            ),
        ),
        migrations.CreateModel(
            name="AdOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "was_shown",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this campaign was selected for display",
                        verbose_name="Was Ad Shown",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        help_text="Unique identifier for the ad request",
                        max_length=100,
                        verbose_name="Request ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Device Type"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Operating System"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=2, verbose_name="Country"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="advertising.placement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Opportunity",
                "verbose_name_plural": "Ad Opportunities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "timestamp"],
                        name="advertising_campaig_8a75ed_idx",
                    ),
                    models.Index(
                        fields=["placement", "timestamp"],
                        name="advertising_placeme_e84012_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="advertising_request_b69692_idx"
                    ),
                ],
            },
        ),
    ]
