# Generated by Django 5.2 on 2025-05-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_campaign_daily_impression_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='daily_impression_target',
        ),
    ]
