# Generated by Django 5.2 on 2025-05-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0006_remove_daily_impression_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='The placement location for this creative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', to='advertising.placement'),
        ),
    ] 