# Generated by Django 5.2.1 on 2025-05-23 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0007_fix_creative_placement_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySpending",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "amount_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount Spent",
                    ),
                ),
                (
                    "budget_exceeded",
                    models.BooleanField(default=False, verbose_name="Budget Exceeded"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_spendings",
                        to="advertising.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Spending",
                "verbose_name_plural": "Daily Spendings",
                "ordering": ["-date"],
                "unique_together": {("campaign", "date")},
            },
        ),
    ]
