# Generated by Django 5.2.1 on 2025-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0008_dailyspending"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="budget_exceeded_action",
            field=models.CharField(
                choices=[
                    ("pause_day", "Pause for the day"),
                    ("pause_campaign", "Pause entire campaign"),
                    ("continue_limited", "Continue with limited frequency"),
                    ("stop_immediately", "Stop serving ads immediately"),
                    ("email_notify", "Email notification only"),
                ],
                default="pause_day",
                help_text="What to do when daily budget is exceeded",
                max_length=20,
                verbose_name="Budget Exceeded Action",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="budget_exceeded_frequency_cap",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maximum ads per user when budget exceeded (for continue_limited action)",
                verbose_name="Budget Exceeded Frequency Cap",
            ),
        ),
    ]
